import { Venue } from './supabase/types'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

export const mockVenues: Venue[] = [
  {
    id: '1',
    host_id: 'host1',
    title: 'דק ים רוטשילד',
    description: 'דק עץ מרהיב מול הים בלב תל אביב. מרחב פתוח ומוצל עם נוף פנורמי לים התיכון. מתאים ל-20 מתאמנים. המסעדה מציעה קפה בוקר חינמי לכל קבוצה.',
    location_address: 'רוטשילד 120',
    location_city: 'תל אביב',
    location_lat: 32.0643,
    location_lng: 34.7680,
    hourly_price: 280,
    capacity: 20,
    space_size_sqm: 80,
    amenities: {
      ac: false, shade: true, toilets: true, shower: false,
      speakers: true, wifi: true, parking: false, sea_view: true,
      natural_light: true, power_outlets: true,
    },
    images: [],
    bonus_offer: 'קפה בוקר חינמי לכל המשתתפים',
    is_active: true,
    created_at: daysAgo(90),
  },
  {
    id: '2',
    host_id: 'host2',
    title: 'גלריה ימית – בר חוף גורדון',
    description: 'חלל ממוזג ומרווח בבר יוקרתי בחוף גורדון. רצפת פרקט, תאורה טבעית ומערכת שמע מקצועית. מושלם לפילאטיס ויוגה.',
    location_address: 'שדרות נורדאו 1',
    location_city: 'תל אביב',
    location_lat: 32.0893,
    location_lng: 34.7700,
    hourly_price: 350,
    capacity: 25,
    space_size_sqm: 100,
    amenities: {
      ac: true, shade: true, toilets: true, shower: true,
      speakers: true, wifi: true, parking: true, sea_view: true,
      natural_light: true, power_outlets: true,
    },
    images: [],
    bonus_offer: 'שוברי הנחה 15% לארוחת ערב לכל משתתף',
    is_active: true,
    created_at: daysAgo(60),
  },
  {
    id: '3',
    host_id: 'host3',
    title: 'מרפסת הילטון – יוגה ובוקר',
    description: 'מרפסת מפוארת עם נוף ישיר לחוף הים. מרחב אינטימי ל-15 מתאמנים עם שמשיות ענקיות. מיזוג זמין בחדר הפנימי.',
    location_address: 'גאורג 205',
    location_city: 'תל אביב',
    location_lat: 32.0880,
    location_lng: 34.7700,
    hourly_price: 420,
    capacity: 15,
    space_size_sqm: 60,
    amenities: {
      ac: true, shade: true, toilets: true, shower: true,
      speakers: false, wifi: true, parking: true, sea_view: true,
      natural_light: true, power_outlets: false,
    },
    images: [],
    bonus_offer: 'מנה מתוקה חינמית מהשף',
    is_active: true,
    created_at: daysAgo(45),
  },
  {
    id: '4',
    host_id: 'host4',
    title: 'גג הכרמל – כרמל אובצ\'ה',
    description: 'גג מרהיב עם נוף 360° לחיפה ולים. פלטפורמת יוגה עם רצפת עץ ייחודית. החלל הכי גבוה ברשת שלנו.',
    location_address: 'שדרות הנשיא 55',
    location_city: 'חיפה',
    location_lat: 32.8100,
    location_lng: 34.9900,
    hourly_price: 240,
    capacity: 18,
    space_size_sqm: 70,
    amenities: {
      ac: false, shade: true, toilets: true, shower: false,
      speakers: true, wifi: true, parking: true, sea_view: true,
      natural_light: true, power_outlets: true,
    },
    images: [],
    bonus_offer: 'מיץ טרי לכל המשתתפים',
    is_active: true,
    created_at: daysAgo(30),
  },
  {
    id: '5',
    host_id: 'host5',
    title: 'בר שמשון – חוף נתניה',
    description: 'מרחב בוקר רגוע ומאוורר מול חוף נתניה הצפוני. רצפת עץ רחבה, מתאים לקבוצות גדולות.',
    location_address: 'טיילת נתניה 8',
    location_city: 'נתניה',
    location_lat: 32.3200,
    location_lng: 34.8530,
    hourly_price: 220,
    capacity: 30,
    space_size_sqm: 110,
    amenities: {
      ac: false, shade: true, toilets: true, shower: true,
      speakers: true, wifi: false, parking: true, sea_view: true,
      natural_light: true, power_outlets: false,
    },
    images: [],
    is_active: true,
    created_at: daysAgo(15),  // "new" venue
  },
  {
    id: '6',
    host_id: 'host6',
    title: 'סיפון כחול – הרצליה פיתוח',
    description: 'בית קפה מעוצב עם גישה לגינה ירוקה. האווירה הכי שלווה בהרצליה. מיזוג + אור טבעי = שיעור מושלם.',
    location_address: 'רחוב הים 3',
    location_city: 'הרצליה',
    location_lat: 32.1620,
    location_lng: 34.8000,
    hourly_price: 310,
    capacity: 22,
    space_size_sqm: 85,
    amenities: {
      ac: true, shade: true, toilets: true, shower: false,
      speakers: true, wifi: true, parking: true, sea_view: false,
      natural_light: true, power_outlets: true,
    },
    images: [],
    bonus_offer: 'ארוחת בוקר בעלות מיוחדת',
    is_active: true,
    created_at: daysAgo(8),   // "new" venue
  },
  {
    id: '7',
    host_id: 'host7',
    title: 'קיבוץ הגלים – שפת הים',
    description: 'חלל ייחודי על שפת הים ממש. אין קירות, רק שמיים, ים ורוח. החוויה הכי אותנטית ברשת.',
    location_address: 'חוף קיבוץ הגלים',
    location_city: 'חיפה',
    location_lat: 32.8300,
    location_lng: 34.9780,
    hourly_price: 195,
    capacity: 20,
    space_size_sqm: 150,
    amenities: {
      ac: false, shade: false, toilets: true, shower: true,
      speakers: false, wifi: false, parking: true, sea_view: true,
      natural_light: true, power_outlets: false,
    },
    images: [],
    is_active: true,
    created_at: daysAgo(5),   // very new
  },
  {
    id: '8',
    host_id: 'host8',
    title: 'בלו ביץ\' – אשדוד הדרומי',
    description: 'ספייס מדיטציה ופילאטיס בקצה הדרומי. שקט, בהיר, מרוחק מהעומס. עם תאורה אמבינטית מיוחדת לשיעורי בוקר.',
    location_address: 'לב ים 12',
    location_city: 'אשדוד',
    location_lat: 31.8044,
    location_lng: 34.6553,
    hourly_price: 180,
    capacity: 16,
    space_size_sqm: 65,
    amenities: {
      ac: true, shade: true, toilets: true, shower: false,
      speakers: true, wifi: true, parking: true, sea_view: true,
      natural_light: true, power_outlets: true,
    },
    images: [],
    bonus_offer: 'סדנת מדיטציה חינמית בסיום',
    is_active: true,
    created_at: daysAgo(3),   // brand new
  },
]

export const amenityLabels: Record<string, { label: string; icon: string }> = {
  ac: { label: 'מיזוג אוויר', icon: '❄️' },
  shade: { label: 'הצללה', icon: '⛱️' },
  toilets: { label: 'שירותים', icon: '🚽' },
  shower: { label: 'מקלחת', icon: '🚿' },
  speakers: { label: 'מערכת שמע', icon: '🔊' },
  wifi: { label: 'Wi-Fi', icon: '📶' },
  parking: { label: 'חניה', icon: '🅿️' },
  sea_view: { label: 'נוף לים', icon: '🌊' },
  natural_light: { label: 'אור טבעי', icon: '☀️' },
  power_outlets: { label: 'שקעי חשמל', icon: '🔌' },
}

// IDs of venues hand-curated as "recommended by platform"
export const RECOMMENDED_VENUE_IDS = ['2', '3', '6']

// Venues created within last 14 days are "new"
export const NEW_VENUE_THRESHOLD_DAYS = 14
