name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_izhIdaUjBzBZUCt3Xrj9ATzS
          VERCEL_PROJECT_ID: prj_YiJ8rTIvPjH886E5zC6JUpHruqDB
